import HomeCompoGroup from "@/components/layouts/home/index.layout";
import Head from "next/head";
import Layout from "@/components/commons/layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>LinkCare</title>
        <meta name="description" content="Generated by LinkCare" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout pageName={"home"}>
        <HomeCompoGroup></HomeCompoGroup>
      </Layout>
    </>
  );
}
